### ISSUE TITLE
Program code - validation fails

### ISSUE THREAD

**Issue by shosein** [EduShareOntario/jobCollectionService#36]
These are the 4 outbound that we are unable to send right now due to the program code being invalid. (i.e. NANC, NAAP, etc…) According to the schema, a valid <ProgramUSISCode> should be 5 characters in length and be the code indicating a discipline or field of study assigned by Stats Can. A previously discussed, we however have some codes in this field that were put in Banner for our own purposes and therefore fail validation. I am unsure if we are allowed to leave it blank or exclude this information section. 
We are checking with Santhosh on his input however, Mike may already have a suggestion.

![program code issue - march 28](https://cloud.githubusercontent.com/assets/15947632/14083047/8cf5da80-f4e1-11e5-8d9c-94b327e34f6e.jpg)

**Comment by mdwmax** [comment]
I modified the code not to populate the program code if it's not numeric, instead of sending 

<AcademicProgram>
 <ProgramUSISCode>NANC</ProgramUSISCode>
  <AcademicProgramType>Major</AcademicProgramType>
  <AcademicProgramName>Undeclared</AcademicProgramName>
</AcademicProgram>

we will send
<AcademicProgram> 
  <AcademicProgramType>Major</AcademicProgramType>
  <AcademicProgramName>Undeclared</AcademicProgramName>
</AcademicProgram>

Change has been promoted to production and the transcripts that were stalled have cleared.
